"""MCI-01 — Mass Casualty Incident Operational Response Runbook Definition.

Provides the declarative definition of the 15 operational steps executed by the
AIMBULENCE runbook engine during a mass-casualty emergency surge.
"""
from typing import List
from backend.app.runbooks.models import (
    RunbookDefinition,
    RunbookStepDefinition,
    SafetyCategory,
)

MCI_01_STEPS: List[RunbookStepDefinition] = [
    RunbookStepDefinition(
        step_id="MCI-01-01",
        step_number=1,
        name="Detect and register MCI incident",
        description="Inspect database for incoming mass casualty dispatch report or verify existing emergency incident record.",
        safety_category=SafetyCategory.GREEN,
        action_tool="detect_incident",
        input_source="incident_id and incoming_casualties parameter",
        expected_output="Validated incident_id, casualty count, location, and severity.",
        verification_requirement="Incident record exists in database.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-02",
        step_number=2,
        name="Verify incident operational details",
        description="Confirm casualty count, estimated time of arrival (ETA), severity level, and geographical triage location.",
        safety_category=SafetyCategory.GREEN,
        action_tool="verify_incident",
        input_source="Incident record from Step 1",
        expected_output="Verified operational parameters: casualty_count >= 1, severity in [HIGH, CRITICAL].",
        verification_requirement="Valid casualty demand threshold.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-03",
        step_number=3,
        name="Read current hospital capacity",
        description="Query live persistent database for emergency department beds, intensive care beds, operating rooms, staff, and blood supply.",
        safety_category=SafetyCategory.GREEN,
        action_tool="get_hospital_capacity",
        input_source="Live operational database via Session",
        expected_output="Live counts of available emergency beds, ICU beds, open ORs, staff on duty, ambulances, blood inventory.",
        verification_requirement="Hospital record and resource counts returned successfully.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-04",
        step_number=4,
        name="Calculate resource shortages for incoming casualties",
        description="Compute acute deficits across beds, critical care, surgical suites, and blood units against incoming casualty demand.",
        safety_category=SafetyCategory.GREEN,
        action_tool="calculate_resource_shortage",
        input_source="Hospital capacity from Step 3 + incoming casualty count",
        expected_output="Deficit matrix (emergency beds, ICU, ORs, blood) and critical shortage flag.",
        verification_requirement="Deficit calculations verified against live hospital baselines.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-05",
        step_number=5,
        name="Create primary MCI coordination task",
        description="Persist the primary hospital-wide MCI response coordination task in the operational task registry.",
        safety_category=SafetyCategory.GREEN,
        action_tool="create_operational_task",
        input_source="Incident title, casualty count, incident_id",
        expected_output="Created task_id in PENDING status.",
        verification_requirement="Operational task persisted in SQLite database.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-06",
        step_number=6,
        name="Inspect available resources",
        description="Enumerate granular status of emergency beds, surgical suites, transport ambulances, and blood inventory.",
        safety_category=SafetyCategory.GREEN,
        action_tool="get_resource_status",
        input_source="Live database resource tables",
        expected_output="Catalog of specific available beds, ambulances, and operating rooms.",
        verification_requirement="Lists of specific resources ready for allocation.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-07",
        step_number=7,
        name="Stage safe available resources",
        description="Reserve available emergency bed (ED-01), dispatch available trauma ambulance (MEDIC-01), and reserve open surgical suite (OR-2).",
        safety_category=SafetyCategory.YELLOW,
        action_tool="stage_safe_resources",
        input_source="Resource inventory from Step 6",
        expected_output="Reservations confirmed for ED-01, MEDIC-01, and OR-2 with audit entries.",
        verification_requirement="Resources verified reserved in SQLite.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-08",
        step_number=8,
        name="Recalculate remaining shortages",
        description="Recompute resource balance after staging all immediately available safe capacity to determine residual unmet demand.",
        safety_category=SafetyCategory.GREEN,
        action_tool="recalculate_shortages",
        input_source="Updated capacity post-Step 7 staging",
        expected_output="Residual deficit matrix highlighting remaining unmet surgical capacity.",
        verification_requirement="Remaining OR deficit calculated.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-09",
        step_number=9,
        name="Identify whether consequential RED action is required",
        description="Assess whether residual surgical deficit demands preempting an occupied operating room scheduled for elective surgery (OR-3).",
        safety_category=SafetyCategory.GREEN,
        action_tool="identify_red_action",
        input_source="Residual shortages from Step 8 and OR inventory from Step 6",
        expected_output="Identification of OR-3 (Elective Arthroscopic Knee Debridement) as the required preemption target.",
        verification_requirement="Consequential action necessity confirmed (OR deficit > 0).",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-10",
        step_number=10,
        name="Propose RED action and pause at TrueForge approval checkpoint",
        description="Generate structured RedActionProposal to preempt OR-3 and halt execution at the TrueForge approval checkpoint awaiting human decision.",
        safety_category=SafetyCategory.RED,
        action_tool="propose_and_pause_red_action",
        input_source="Target resource OR-3, incident_id, and clinical trade-offs",
        expected_output="TrueForge checkpoint created in tool.approval_required state; Runbook transitions to WAITING_FOR_APPROVAL.",
        verification_requirement="Audit record CHECKPOINT_CREATED in SQLite.",
        failure_behavior="BLOCK_FOR_ESCALATION",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-11",
        step_number=11,
        name="Execute authorized consequential action or process rejection",
        description="Inspect TrueForge approval decision. If authorized, consume single-use token and mutate OR-3 to RESERVED_FOR_TRAUMA; if denied, block runbook.",
        safety_category=SafetyCategory.RED,
        action_tool="execute_approved_consequential_action",
        input_source="Checkpoint decision and authorization token from Step 10",
        expected_output="OR-3 mutated to RESERVED_FOR_TRAUMA (if approved) OR runbook marked BLOCKED without mutation (if denied).",
        verification_requirement="Authorization token validated and consumed on execution.",
        failure_behavior="BLOCK_FOR_ESCALATION",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-12",
        step_number=12,
        name="Verify resulting operational state",
        description="Perform direct database verification to confirm OR-3 status is RESERVED_FOR_TRAUMA and emergency clearance flag is active on disk.",
        safety_category=SafetyCategory.GREEN,
        action_tool="verify_consequential_state",
        input_source="Target resource OR-3 and database state",
        expected_output="State verification confirmed on disk (status == RESERVED_FOR_TRAUMA, is_emergency_cleared == True).",
        verification_requirement="verify_operational_status returns verified=True.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-13",
        step_number=13,
        name="Recalculate hospital capacity and remaining shortages",
        description="Query live capacity post-preemption to confirm surgical capacity deficit is resolved.",
        safety_category=SafetyCategory.GREEN,
        action_tool="recalculate_final_shortages",
        input_source="Live database state post-OR-3 preemption",
        expected_output="Final capacity assessment showing surgical deficit resolved to 0.",
        verification_requirement="Shortage recalculation reflects newly unlocked trauma surgical capacity.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-14",
        step_number=14,
        name="Create follow-up operational tasks and notifications",
        description="Create follow-up operational coordination tasks to notify orthopedic surgical teams and alert the blood bank.",
        safety_category=SafetyCategory.GREEN,
        action_tool="create_followup_tasks",
        input_source="Consequential execution results and incident context",
        expected_output="Follow-up operational tasks created in database for surgical notification and blood bank alert.",
        verification_requirement="Follow-up tasks verified in SQLite.",
        failure_behavior="FAIL_RUNBOOK",
    ),
    RunbookStepDefinition(
        step_id="MCI-01-15",
        step_number=15,
        name="Generate final runbook execution summary",
        description="Synthesize operational runbook audit trail, resource metrics, approval decisions, and final surge readiness report.",
        safety_category=SafetyCategory.GREEN,
        action_tool="generate_execution_summary",
        input_source="Execution context across all completed steps",
        expected_output="Comprehensive JSON summary report containing operational timeline, resources allocated, audit hashes, and final status.",
        verification_requirement="Final execution state persisted in SQLite as COMPLETED.",
        failure_behavior="FAIL_RUNBOOK",
    ),
]


def get_mci_01_definition() -> RunbookDefinition:
    """Return the official MCI-01 Runbook Definition instance."""
    return RunbookDefinition(
        runbook_id="MCI-01",
        title="Mass Casualty Incident (MCI) Operational Surge Response",
        description=(
            "Deterministic 15-step operational runbook for executing acute hospital surge mobilization, "
            "safe resource staging, TrueForge human-in-the-loop consequential approval, state mutation, "
            "independent verification, and audit trail generation."
        ),
        version="1.0.0",
        steps=MCI_01_STEPS,
    )
