"""Pydantic schemas and enums for runbook actions, safety tiers, and audit events."""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class ActionSafetyTier(str, Enum):
    """Safety classification defining autonomous execution authority."""
    GREEN = "GREEN"    # Safe / Reversible: Automatic execution
    YELLOW = "YELLOW"  # Confirmation: Minor operational impact
    RED = "RED"        # High Consequence: Strict Human Approval Gate required


class ActionStatus(str, Enum):
    """Lifecycle statuses of an operational runbook action."""
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class ActionProposal(BaseModel):
    """Structured action generated by an agent or runbook step."""
    action_id: str = Field(..., description="Unique action identifier")
    name: str = Field(..., description="Action name or command")
    tier: ActionSafetyTier = Field(..., description="Safety classification tier")
    description: str = Field(..., description="Human-readable summary of the action")
    rationale: str = Field(..., description="Operational justification and shortage context")
    affected_resources: List[str] = Field(default_factory=list, description="Specific assets or wards impacted")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Execution parameters")
    requires_human_approval: bool = Field(..., description="Whether action requires explicit approval")
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ActionResponse(BaseModel):
    """Outcome and authorization state of an action."""
    action_id: str
    status: ActionStatus
    approved_by: Optional[str] = None
    decision_note: Optional[str] = None
    executed_at: Optional[datetime] = None
    execution_result: Optional[Dict[str, Any]] = None
    verified: bool = False

    model_config = ConfigDict(from_attributes=True)


class AuditEvent(BaseModel):
    """Immutable audit trail record documenting operational system actions."""
    id: str
    incident_id: Optional[str] = None
    event_type: str = Field(..., description="Type of event, e.g. INCIDENT_REPORTED, ACTION_PROPOSED, APPROVAL_GRANTED")
    action_name: Optional[str] = None
    tier: Optional[ActionSafetyTier] = None
    details: Dict[str, Any] = Field(default_factory=dict)
    performed_by: str = Field(default="SYSTEM", description="Actor who initiated: SYSTEM, AGENT, or OPERATOR")
    timestamp: datetime

    model_config = ConfigDict(from_attributes=True)
